import { Inter } from "next/font/google";
import Script from 'next/script';
import { ThemeProvider } from 'next-themes'
import "./globals.css";

const inter = Inter({ 
  subsets: ["latin"],
  weight:["200","300","400","600","700","800"],
  variable: '--font-inter',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Script src="https://kit.fontawesome.com/5ab2500a75.js" crossOrigin="anonymous" strategy="beforeInteractive"></Script>
      <body className={`bg-neutral-200 dark:bg-neutral-900 ${inter.className}`}>
        <ThemeProvider attribute="class">{children}</ThemeProvider>
      </body>
    </html>
  );
}
